# Extensions
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/environments/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'log/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'swagger/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantInterpolation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'config/initializers/*'
Rails/UnknownEnv:
  Environments:
    - development
    - test
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Layout/LineLength:
  Max: 150
