# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bootsnap', require: false
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.2.2', '>= 7.2.2.1'
gem 'tzinfo-data', platforms: %i[windows jruby]

gem 'aasm'
gem 'doorkeeper'
gem 'faraday'
gem 'faraday-retry'
gem 'groq'
gem 'jsonapi-serializer'
gem 'oj'
gem 'rack-cors'
gem 'sidekiq'
gem 'sidekiq-scheduler'

group :development, :test do
  gem 'awesome_print'
  gem 'bullet'
  gem 'database_cleaner'
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'ffaker'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'tilt'
  gem 'vcr'

  gem 'rubocop', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rspec_rails', require: false
  gem 'rubocop-thread_safety', require: false
end

group :test do
  gem 'json_matchers'
  gem 'rspec-json_expectations'
  gem 'rspec-retry'
  gem 'shoulda-matchers', require: false
  gem 'simplecov', require: false
  gem 'super_diff'
  gem 'webmock'
end
